### ISSUE TITLE
“deduplicate” is not working properly

### ISSUE THREAD

**Issue by Kyle-Ye** [MartinNey/hust-courses-to-ics#16]
非常抱歉打扰了，但这里这个deduplicate的实现貌似对于同时同地同名课程的多个老师生成多个课程
![截屏2020-02-1710 36 33](https://user-images.githubusercontent.com/43724855/74619700-607a3f00-5171-11ea-896a-afae706ce5e8.png)
如图，对于这里的马原课程ics则会生成两个，对于开启了提醒的话会提醒两次，有时间的话可以合并一下吗？

**Comment by Kyle-Ye** [comment]
以及上一个commit之后，现在test没对应地修改会直接fail

**Comment by MMMartt** [comment]
OK，测试 fail 搞好了。deduplicate 的预期应该是这样子的，如果要另外整一个 key 值不对比的话，我这两天晚点再弄一下。

**Comment by Kyle-Ye** [comment]
> OK，测试 fail 搞好了。deduplicate 的预期应该是这样子的，如果要另外整一个 key 值不对比的话，我这两天晚点再弄一下。

谢啦，因为不太会JS，目前我是很urgely的手动把.ics文件读出来然后用正则再合并 😭

**Comment by ManiaciaChao** [comment]
> 
> 
> 以及上一个commit之后，现在test没对应地修改会直接fail

之前test忘改，我的锅我的锅。

“同时同地同名课程的多个老师”会在什么情况下出现呢？我目前还没遇到这种情况。

**Comment by Kyle-Ye** [comment]
> > 以及上一个commit之后，现在test没对应地修改会直接fail
> 
> 之前test忘改，我的锅我的锅。
> 
> “同时同地同名课程的多个老师”会在什么情况下出现呢？我目前还没遇到这种情况。

见我上面的图，比如这学期的部分专业的毛概课，老师会从A -> A、B -> A、C，在后面两个阶段，会被误解析为两个event

**Comment by MMMartt** [comment]
fix in #17
