### ISSUE TITLE
Duration and Repeat Question

### ISSUE THREAD

**Issue by Kyle-Ye** [MartinNey/hust-courses-to-ics#19]
It seems the current project didn't need duration and repeat.( I changed the duration and repeat, but nothing changes, at least in my iOS and Mac devices)

I alse looked it up at https://icalendar.org/iCalendar-RFC-5545/3-3-6-duration.html, it says

> Negative durations are typically used to schedule an alarm to trigger before an associated time (see Section 3.8.6.3).

But we already have trigger time to indicate it, so what's the duration and repeat mean and for?

**Comment by ManiaciaChao** [comment]
鉴于目前每节课都是单独的event，这个repeat确实没什么用。
