### ISSUE TITLE
Please add the config to modify reminding time of class

### ISSUE THREAD

**Issue by viseator** [MartinNey/hust-courses-to-ics#2]
The default reminding time is ahead of 10 mins, which is not suitable for us.

**Comment by MMMartt** [comment]
Actually, there shouldn't be any event alert. I [never add something like that](https://github.com/MMMartt/hust-courses-to-ics/blob/master/src/json-to-ical.js#L33-L50).

If alert occurs on your device, it's supposed to be default behavior of your App, please check it.

Well, but [adding alert](https://tools.ietf.org/html/rfc5545#section-3.6.6) seems to be useful, I will try to add this feature XDD.

**Comment by MMMartt** [comment]
[feature added](https://github.com/MMMartt/hust-courses-to-ics/commit/b777d5962f184d0bcc0e42684441c80d036f5a82) XD
